# Generated by Django 3.1.2 on 2020-11-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCatalogue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=500)),
                ('docker_image', models.CharField(max_length=500)),
                ('cpu', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('process_name', models.CharField(max_length=50)),
                ('process_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
