# Generated by Django 3.1.2 on 2020-11-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcatalogue',
            name='cpu_limit',
            field=models.CharField(default='500m', max_length=50),
        ),
        migrations.AddField(
            model_name='processcatalogue',
            name='memory_limit',
            field=models.CharField(default='256MiB', max_length=50),
        ),
    ]
