# Generated by Django 3.1.2 on 2020-11-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odp', '0003_auto_20201121_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcatalogue',
            name='process_description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='processcatalogue',
            name='process_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
